sonar.projectKey=qa_app
sonar.projectName=qa_app
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=**/vendor/**,**/node_modules/**,**/storage/**,**/cache/**,**/logs/**,**/.git/**,**/tmp/**

sonar.sourceEncoding=UTF-8
sonar.host.url=http://localhost:9000
sonar.token=sqp_[REDACTED-SONAR-TOKEN-LAB]